import 'dart:developer' as developer;
import 'dart:typed_data';

import 'package:audioplayers/audioplayers.dart';

import 'replay_tone_generator.dart';

// ── ReplayAudioController (M111) ──────────────────────────────────────────────

/// Manages cinematic audio playback during the travel replay (M111).
///
/// Uses synthesised WAV tones generated by [ReplayToneGenerator] rather than
/// bundled asset files. Tones are generated once in [preload] and cached as
/// [Uint8List] so every subsequent play call is instant.
///
/// Wraps five dedicated [AudioPlayer] instances — one per sound slot — so
/// overlapping audio is handled correctly (e.g. a whoosh can finish while an
/// arrival chime starts).
///
/// | Slot        | Sound design                          | Trigger              |
/// |-------------|---------------------------------------|----------------------|
/// | travelShort | band-limited noise whoosh, 0.25 s     | flight < 20° arc     |
/// | travelLong  | slower noise whoosh, 0.55 s           | flight ≥ 20° arc     |
/// | arrival     | bell chime (880 Hz + harmonics)       | pulse phase start    |
/// | achievement | ascending arpeggio C5–E5–G5–C6        | achievement overlay  |
/// | end         | arpeggio + major chord fanfare        | replay complete      |
class ReplayAudioController {
  ReplayAudioController()
      : _travelShort = AudioPlayer(),
        _travelLong = AudioPlayer(),
        _arrival = AudioPlayer(),
        _achievement = AudioPlayer(),
        _end = AudioPlayer() {
    for (final p in _allPlayers) {
      p.setReleaseMode(ReleaseMode.stop).ignore();
    }
  }

  final AudioPlayer _travelShort;
  final AudioPlayer _travelLong;
  final AudioPlayer _arrival;
  final AudioPlayer _achievement;
  final AudioPlayer _end;

  /// When true, all [play*] methods are no-ops. Audio already in progress is
  /// stopped. Toggle from the mute button in [GlobeReplayWidget].
  bool isMuted = false;

  // Cached synthesised WAV bytes — generated once in [preload].
  Uint8List? _shortBytes;
  Uint8List? _longBytes;
  Uint8List? _arrivalBytes;
  Uint8List? _achievementBytes;
  Uint8List? _endBytes;

  // ── Public API ─────────────────────────────────────────────────────────────

  /// Synthesises all tones and warms up audio players.
  ///
  /// Call this before [TravelReplayController.play] so the first playback has
  /// minimal latency. Safe to call multiple times (generation is idempotent).
  Future<void> preload() async {
    // Generate bytes (cheap CPU work — runs synchronously).
    _shortBytes ??= ReplayToneGenerator.shortWhoosh();
    _longBytes ??= ReplayToneGenerator.longWhoosh();
    _arrivalBytes ??= ReplayToneGenerator.arrival();
    _achievementBytes ??= ReplayToneGenerator.achievement();
    _endBytes ??= ReplayToneGenerator.replayEnd();

    // Warm up each player by setting the source without playing.
    await Future.wait([
      _warmUp(_travelShort, _shortBytes!),
      _warmUp(_travelLong, _longBytes!),
      _warmUp(_arrival, _arrivalBytes!),
      _warmUp(_achievement, _achievementBytes!),
      _warmUp(_end, _endBytes!),
    ]);
  }

  /// Plays a travel movement whoosh appropriate to [arcDistanceDeg].
  void playTravelMovement(double arcDistanceDeg) {
    if (isMuted) return;
    if (arcDistanceDeg < 20.0) {
      _play(_travelShort, _shortBytes);
    } else {
      _play(_travelLong, _longBytes);
    }
  }

  /// Plays the arrival bell chime.
  void playArrival() {
    if (isMuted) return;
    _play(_arrival, _arrivalBytes);
  }

  /// Plays the achievement arpeggio.
  void playAchievement() {
    if (isMuted) return;
    _play(_achievement, _achievementBytes);
  }

  /// Plays the end fanfare.
  void playReplayEnd() {
    if (isMuted) return;
    _play(_end, _endBytes);
  }

  /// Stops all currently active audio immediately.
  void stopAll() {
    for (final p in _allPlayers) {
      p.stop().ignore();
    }
  }

  void dispose() {
    for (final p in _allPlayers) {
      p.dispose();
    }
  }

  // ── Internal ───────────────────────────────────────────────────────────────

  List<AudioPlayer> get _allPlayers =>
      [_travelShort, _travelLong, _arrival, _achievement, _end];

  Future<void> _warmUp(AudioPlayer player, Uint8List bytes) async {
    try {
      await player.setSource(BytesSource(bytes, mimeType: 'audio/wav'));
    } catch (e) {
      developer.log('ReplayAudio: warm-up failed: $e');
    }
  }

  void _play(AudioPlayer player, Uint8List? bytes) {
    if (bytes == null) return;
    try {
      player.play(BytesSource(bytes, mimeType: 'audio/wav')).ignore();
    } catch (e) {
      developer.log('ReplayAudio: play failed: $e');
    }
  }
}
