// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Hu0Ei9jbVPM2PqMUZTciihftOo_K2E4',
    appId: '1:457696483088:web:a6663bda11aecca9833795',
    messagingSenderId: '457696483088',
    projectId: 'roavvy-prod',
    authDomain: 'roavvy-prod.firebaseapp.com',
    storageBucket: 'roavvy-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1uR4VnLcRjFGkzVtXx8CPn19oaXaZqno',
    appId: '1:457696483088:android:d45d35618eab541e833795',
    messagingSenderId: '457696483088',
    projectId: 'roavvy-prod',
    storageBucket: 'roavvy-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADg5WoQbOffywqD07Nbc-hk2I8KcIEXxY',
    appId: '1:457696483088:ios:d216ead61ed56683833795',
    messagingSenderId: '457696483088',
    projectId: 'roavvy-prod',
    storageBucket: 'roavvy-prod.firebasestorage.app',
    iosBundleId: 'com.roavvy.prod',
  );
}
