/// ISO 3166-2 → English display name.
///
/// Lookup falls back to the ISO code itself when absent (see ADR-019).
/// Generated from the Natural Earth admin1 1:10m dataset.
const Map<String, String> kRegionNames = {
  // ── United States ─────────────────────────────────────────────────────────
  'US-AL': 'Alabama',
  'US-AK': 'Alaska',
  'US-AZ': 'Arizona',
  'US-AR': 'Arkansas',
  'US-CA': 'California',
  'US-CO': 'Colorado',
  'US-CT': 'Connecticut',
  'US-DC': 'District of Columbia',
  'US-DE': 'Delaware',
  'US-FL': 'Florida',
  'US-GA': 'Georgia',
  'US-HI': 'Hawaii',
  'US-ID': 'Idaho',
  'US-IL': 'Illinois',
  'US-IN': 'Indiana',
  'US-IA': 'Iowa',
  'US-KS': 'Kansas',
  'US-KY': 'Kentucky',
  'US-LA': 'Louisiana',
  'US-ME': 'Maine',
  'US-MD': 'Maryland',
  'US-MA': 'Massachusetts',
  'US-MI': 'Michigan',
  'US-MN': 'Minnesota',
  'US-MS': 'Mississippi',
  'US-MO': 'Missouri',
  'US-MT': 'Montana',
  'US-NE': 'Nebraska',
  'US-NV': 'Nevada',
  'US-NH': 'New Hampshire',
  'US-NJ': 'New Jersey',
  'US-NM': 'New Mexico',
  'US-NY': 'New York',
  'US-NC': 'North Carolina',
  'US-ND': 'North Dakota',
  'US-OH': 'Ohio',
  'US-OK': 'Oklahoma',
  'US-OR': 'Oregon',
  'US-PA': 'Pennsylvania',
  'US-RI': 'Rhode Island',
  'US-SC': 'South Carolina',
  'US-SD': 'South Dakota',
  'US-TN': 'Tennessee',
  'US-TX': 'Texas',
  'US-UT': 'Utah',
  'US-VT': 'Vermont',
  'US-VA': 'Virginia',
  'US-WA': 'Washington',
  'US-WV': 'West Virginia',
  'US-WI': 'Wisconsin',
  'US-WY': 'Wyoming',

  // ── United Kingdom ────────────────────────────────────────────────────────
  'GB-ENG': 'England',
  'GB-NIR': 'Northern Ireland',
  'GB-SCT': 'Scotland',
  'GB-WLS': 'Wales',

  // ── France (metropolitan regions) ─────────────────────────────────────────
  'FR-ARA': 'Auvergne-Rhône-Alpes',
  'FR-BFC': 'Bourgogne-Franche-Comté',
  'FR-BRE': 'Bretagne',
  'FR-CVL': 'Centre-Val de Loire',
  'FR-COR': 'Corse',
  'FR-GES': 'Grand Est',
  'FR-HDF': 'Hauts-de-France',
  'FR-IDF': 'Île-de-France',
  'FR-NAQ': 'Nouvelle-Aquitaine',
  'FR-NOR': 'Normandie',
  'FR-OCC': 'Occitanie',
  'FR-PAC': "Provence-Alpes-Côte d'Azur",
  'FR-PDL': 'Pays de la Loire',

  // ── Germany (Länder) ──────────────────────────────────────────────────────
  'DE-BB': 'Brandenburg',
  'DE-BE': 'Berlin',
  'DE-BW': 'Baden-Württemberg',
  'DE-BY': 'Bavaria',
  'DE-HB': 'Bremen',
  'DE-HE': 'Hesse',
  'DE-HH': 'Hamburg',
  'DE-MV': 'Mecklenburg-Vorpommern',
  'DE-NI': 'Lower Saxony',
  'DE-NW': 'North Rhine-Westphalia',
  'DE-RP': 'Rhineland-Palatinate',
  'DE-SH': 'Schleswig-Holstein',
  'DE-SL': 'Saarland',
  'DE-SN': 'Saxony',
  'DE-ST': 'Saxony-Anhalt',
  'DE-TH': 'Thuringia',

  // ── Australia ─────────────────────────────────────────────────────────────
  'AU-ACT': 'Australian Capital Territory',
  'AU-NSW': 'New South Wales',
  'AU-NT': 'Northern Territory',
  'AU-QLD': 'Queensland',
  'AU-SA': 'South Australia',
  'AU-TAS': 'Tasmania',
  'AU-VIC': 'Victoria',
  'AU-WA': 'Western Australia',

  // ── Canada ────────────────────────────────────────────────────────────────
  'CA-AB': 'Alberta',
  'CA-BC': 'British Columbia',
  'CA-MB': 'Manitoba',
  'CA-NB': 'New Brunswick',
  'CA-NL': 'Newfoundland and Labrador',
  'CA-NS': 'Nova Scotia',
  'CA-NT': 'Northwest Territories',
  'CA-NU': 'Nunavut',
  'CA-ON': 'Ontario',
  'CA-PE': 'Prince Edward Island',
  'CA-QC': 'Quebec',
  'CA-SK': 'Saskatchewan',
  'CA-YT': 'Yukon',

  // ── Italy ─────────────────────────────────────────────────────────────────
  'IT-65': 'Abruzzo',
  'IT-77': 'Basilicata',
  'IT-78': 'Calabria',
  'IT-72': 'Campania',
  'IT-45': 'Emilia-Romagna',
  'IT-36': 'Friuli-Venezia Giulia',
  'IT-62': 'Lazio',
  'IT-42': 'Liguria',
  'IT-25': 'Lombardy',
  'IT-57': 'Marche',
  'IT-67': 'Molise',
  'IT-21': 'Piedmont',
  'IT-75': 'Apulia',
  'IT-88': 'Sardinia',
  'IT-82': 'Sicily',
  'IT-52': 'Tuscany',
  'IT-32': 'Trentino-South Tyrol',
  'IT-55': 'Umbria',
  'IT-23': 'Aosta Valley',
  'IT-34': 'Veneto',

  // ── Spain ─────────────────────────────────────────────────────────────────
  'ES-AN': 'Andalusia',
  'ES-AR': 'Aragon',
  'ES-AS': 'Asturias',
  'ES-CN': 'Canary Islands',
  'ES-CB': 'Cantabria',
  'ES-CL': 'Castile and León',
  'ES-CM': 'Castilla-La Mancha',
  'ES-CT': 'Catalonia',
  'ES-CE': 'Ceuta',
  'ES-EX': 'Extremadura',
  'ES-GA': 'Galicia',
  'ES-IB': 'Balearic Islands',
  'ES-RI': 'La Rioja',
  'ES-MD': 'Community of Madrid',
  'ES-ML': 'Melilla',
  'ES-MC': 'Region of Murcia',
  'ES-NC': 'Navarre',
  'ES-PV': 'Basque Country',
  'ES-VC': 'Valencian Community',

  // ── Japan (prefectures) ───────────────────────────────────────────────────
  'JP-01': 'Hokkaido',
  'JP-02': 'Aomori',
  'JP-03': 'Iwate',
  'JP-04': 'Miyagi',
  'JP-05': 'Akita',
  'JP-06': 'Yamagata',
  'JP-07': 'Fukushima',
  'JP-08': 'Ibaraki',
  'JP-09': 'Tochigi',
  'JP-10': 'Gunma',
  'JP-11': 'Saitama',
  'JP-12': 'Chiba',
  'JP-13': 'Tokyo',
  'JP-14': 'Kanagawa',
  'JP-15': 'Niigata',
  'JP-16': 'Toyama',
  'JP-17': 'Ishikawa',
  'JP-18': 'Fukui',
  'JP-19': 'Yamanashi',
  'JP-20': 'Nagano',
  'JP-21': 'Gifu',
  'JP-22': 'Shizuoka',
  'JP-23': 'Aichi',
  'JP-24': 'Mie',
  'JP-25': 'Shiga',
  'JP-26': 'Kyoto',
  'JP-27': 'Osaka',
  'JP-28': 'Hyogo',
  'JP-29': 'Nara',
  'JP-30': 'Wakayama',
  'JP-31': 'Tottori',
  'JP-32': 'Shimane',
  'JP-33': 'Okayama',
  'JP-34': 'Hiroshima',
  'JP-35': 'Yamaguchi',
  'JP-36': 'Tokushima',
  'JP-37': 'Kagawa',
  'JP-38': 'Ehime',
  'JP-39': 'Kochi',
  'JP-40': 'Fukuoka',
  'JP-41': 'Saga',
  'JP-42': 'Nagasaki',
  'JP-43': 'Kumamoto',
  'JP-44': 'Oita',
  'JP-45': 'Miyazaki',
  'JP-46': 'Kagoshima',
  'JP-47': 'Okinawa',

  // ── Portugal ──────────────────────────────────────────────────────────────
  'PT-01': 'Aveiro',
  'PT-02': 'Beja',
  'PT-03': 'Braga',
  'PT-04': 'Bragança',
  'PT-05': 'Castelo Branco',
  'PT-06': 'Coimbra',
  'PT-07': 'Évora',
  'PT-08': 'Faro',
  'PT-09': 'Guarda',
  'PT-10': 'Leiria',
  'PT-11': 'Lisbon',
  'PT-12': 'Portalegre',
  'PT-13': 'Porto',
  'PT-14': 'Santarém',
  'PT-15': 'Setúbal',
  'PT-16': 'Viana do Castelo',
  'PT-17': 'Vila Real',
  'PT-18': 'Viseu',
  'PT-20': 'Azores',
  'PT-30': 'Madeira',

  // ── Netherlands ───────────────────────────────────────────────────────────
  'NL-DR': 'Drenthe',
  'NL-FL': 'Flevoland',
  'NL-FR': 'Friesland',
  'NL-GE': 'Gelderland',
  'NL-GR': 'Groningen',
  'NL-LI': 'Limburg',
  'NL-NB': 'North Brabant',
  'NL-NH': 'North Holland',
  'NL-OV': 'Overijssel',
  'NL-UT': 'Utrecht',
  'NL-ZE': 'Zeeland',
  'NL-ZH': 'South Holland',

  // ── Belgium ───────────────────────────────────────────────────────────────
  'BE-BRU': 'Brussels',
  'BE-VLG': 'Flemish Region',
  'BE-WAL': 'Wallonia',

  // ── Switzerland ───────────────────────────────────────────────────────────
  'CH-AG': 'Aargau',
  'CH-AR': 'Appenzell Ausserrhoden',
  'CH-AI': 'Appenzell Innerrhoden',
  'CH-BL': 'Basel-Landschaft',
  'CH-BS': 'Basel-Stadt',
  'CH-BE': 'Bern',
  'CH-FR': 'Fribourg',
  'CH-GE': 'Geneva',
  'CH-GL': 'Glarus',
  'CH-GR': 'Graubünden',
  'CH-JU': 'Jura',
  'CH-LU': 'Lucerne',
  'CH-NE': 'Neuchâtel',
  'CH-NW': 'Nidwalden',
  'CH-OW': 'Obwalden',
  'CH-SG': 'St. Gallen',
  'CH-SH': 'Schaffhausen',
  'CH-SZ': 'Schwyz',
  'CH-SO': 'Solothurn',
  'CH-TG': 'Thurgau',
  'CH-TI': 'Ticino',
  'CH-UR': 'Uri',
  'CH-VS': 'Valais',
  'CH-VD': 'Vaud',
  'CH-ZG': 'Zug',
  'CH-ZH': 'Zurich',

  // ── Austria ───────────────────────────────────────────────────────────────
  'AT-1': 'Burgenland',
  'AT-2': 'Carinthia',
  'AT-3': 'Lower Austria',
  'AT-4': 'Upper Austria',
  'AT-5': 'Salzburg',
  'AT-6': 'Styria',
  'AT-7': 'Tyrol',
  'AT-8': 'Vorarlberg',
  'AT-9': 'Vienna',

  // ── Greece ────────────────────────────────────────────────────────────────
  'GR-A': 'East Macedonia and Thrace',
  'GR-B': 'Central Macedonia',
  'GR-C': 'West Macedonia',
  'GR-D': 'Epirus',
  'GR-E': 'Thessaly',
  'GR-F': 'Ionian Islands',
  'GR-G': 'West Greece',
  'GR-H': 'Central Greece',
  'GR-I': 'Attica',
  'GR-J': 'Peloponnese',
  'GR-K': 'North Aegean',
  'GR-L': 'South Aegean',
  'GR-M': 'Crete',

  // ── Thailand ──────────────────────────────────────────────────────────────
  'TH-10': 'Bangkok',
  'TH-11': 'Samut Prakan',
  'TH-21': 'Chanthaburi',
  'TH-50': 'Chiang Mai',
  'TH-51': 'Lamphun',
  'TH-52': 'Lampang',
  'TH-56': 'Phayao',
  'TH-57': 'Chiang Rai',
  'TH-67': 'Phetchabun',
  'TH-76': 'Phetchaburi',
  'TH-77': 'Prachuap Khiri Khan',
  'TH-83': 'Phuket',
  'TH-84': 'Surat Thani',
  'TH-85': 'Ranong',
  'TH-86': 'Chumphon',

  // ── India ─────────────────────────────────────────────────────────────────
  'IN-AN': 'Andaman and Nicobar Islands',
  'IN-AP': 'Andhra Pradesh',
  'IN-AR': 'Arunachal Pradesh',
  'IN-AS': 'Assam',
  'IN-BR': 'Bihar',
  'IN-CH': 'Chandigarh',
  'IN-CT': 'Chhattisgarh',
  'IN-DN': 'Dadra and Nagar Haveli',
  'IN-DD': 'Daman and Diu',
  'IN-DL': 'Delhi',
  'IN-GA': 'Goa',
  'IN-GJ': 'Gujarat',
  'IN-HR': 'Haryana',
  'IN-HP': 'Himachal Pradesh',
  'IN-JK': 'Jammu and Kashmir',
  'IN-JH': 'Jharkhand',
  'IN-KA': 'Karnataka',
  'IN-KL': 'Kerala',
  'IN-LD': 'Lakshadweep',
  'IN-MP': 'Madhya Pradesh',
  'IN-MH': 'Maharashtra',
  'IN-MN': 'Manipur',
  'IN-ML': 'Meghalaya',
  'IN-MZ': 'Mizoram',
  'IN-NL': 'Nagaland',
  'IN-OR': 'Odisha',
  'IN-PY': 'Puducherry',
  'IN-PB': 'Punjab',
  'IN-RJ': 'Rajasthan',
  'IN-SK': 'Sikkim',
  'IN-TN': 'Tamil Nadu',
  'IN-TG': 'Telangana',
  'IN-TR': 'Tripura',
  'IN-UP': 'Uttar Pradesh',
  'IN-UT': 'Uttarakhand',
  'IN-WB': 'West Bengal',

  // ── China ─────────────────────────────────────────────────────────────────
  'CN-AH': 'Anhui',
  'CN-BJ': 'Beijing',
  'CN-CQ': 'Chongqing',
  'CN-FJ': 'Fujian',
  'CN-GS': 'Gansu',
  'CN-GD': 'Guangdong',
  'CN-GX': 'Guangxi',
  'CN-GZ': 'Guizhou',
  'CN-HI': 'Hainan',
  'CN-HE': 'Hebei',
  'CN-HL': 'Heilongjiang',
  'CN-HA': 'Henan',
  'CN-HB': 'Hubei',
  'CN-HN': 'Hunan',
  'CN-JS': 'Jiangsu',
  'CN-JX': 'Jiangxi',
  'CN-JL': 'Jilin',
  'CN-LN': 'Liaoning',
  'CN-NM': 'Inner Mongolia',
  'CN-NX': 'Ningxia',
  'CN-QH': 'Qinghai',
  'CN-SN': 'Shaanxi',
  'CN-SD': 'Shandong',
  'CN-SH': 'Shanghai',
  'CN-SX': 'Shanxi',
  'CN-SC': 'Sichuan',
  'CN-TJ': 'Tianjin',
  'CN-XJ': 'Xinjiang',
  'CN-XZ': 'Tibet',
  'CN-YN': 'Yunnan',
  'CN-ZJ': 'Zhejiang',

  // ── Brazil ────────────────────────────────────────────────────────────────
  'BR-AC': 'Acre',
  'BR-AL': 'Alagoas',
  'BR-AP': 'Amapá',
  'BR-AM': 'Amazonas',
  'BR-BA': 'Bahia',
  'BR-CE': 'Ceará',
  'BR-DF': 'Distrito Federal',
  'BR-ES': 'Espírito Santo',
  'BR-GO': 'Goiás',
  'BR-MA': 'Maranhão',
  'BR-MT': 'Mato Grosso',
  'BR-MS': 'Mato Grosso do Sul',
  'BR-MG': 'Minas Gerais',
  'BR-PA': 'Pará',
  'BR-PB': 'Paraíba',
  'BR-PR': 'Paraná',
  'BR-PE': 'Pernambuco',
  'BR-PI': 'Piauí',
  'BR-RJ': 'Rio de Janeiro',
  'BR-RN': 'Rio Grande do Norte',
  'BR-RS': 'Rio Grande do Sul',
  'BR-RO': 'Rondônia',
  'BR-RR': 'Roraima',
  'BR-SC': 'Santa Catarina',
  'BR-SP': 'São Paulo',
  'BR-SE': 'Sergipe',
  'BR-TO': 'Tocantins',

  // ── Mexico ────────────────────────────────────────────────────────────────
  'MX-AGU': 'Aguascalientes',
  'MX-BCN': 'Baja California',
  'MX-BCS': 'Baja California Sur',
  'MX-CAM': 'Campeche',
  'MX-CHP': 'Chiapas',
  'MX-CHH': 'Chihuahua',
  'MX-CMX': 'Mexico City',
  'MX-COA': 'Coahuila',
  'MX-COL': 'Colima',
  'MX-DUR': 'Durango',
  'MX-GUA': 'Guanajuato',
  'MX-GRO': 'Guerrero',
  'MX-HID': 'Hidalgo',
  'MX-JAL': 'Jalisco',
  'MX-MEX': 'State of Mexico',
  'MX-MIC': 'Michoacán',
  'MX-MOR': 'Morelos',
  'MX-NAY': 'Nayarit',
  'MX-NLE': 'Nuevo León',
  'MX-OAX': 'Oaxaca',
  'MX-PUE': 'Puebla',
  'MX-QUE': 'Querétaro',
  'MX-ROO': 'Quintana Roo',
  'MX-SLP': 'San Luis Potosí',
  'MX-SIN': 'Sinaloa',
  'MX-SON': 'Sonora',
  'MX-TAB': 'Tabasco',
  'MX-TAM': 'Tamaulipas',
  'MX-TLA': 'Tlaxcala',
  'MX-VER': 'Veracruz',
  'MX-YUC': 'Yucatán',
  'MX-ZAC': 'Zacatecas',

  // ── New Zealand ───────────────────────────────────────────────────────────
  'NZ-AUK': 'Auckland',
  'NZ-BOP': 'Bay of Plenty',
  'NZ-CAN': 'Canterbury',
  'NZ-GIS': 'Gisborne',
  'NZ-HKB': "Hawke's Bay",
  'NZ-MWT': 'Manawatū-Whanganui',
  'NZ-MBH': 'Marlborough',
  'NZ-NSN': 'Nelson',
  'NZ-NTL': 'Northland',
  'NZ-OTA': 'Otago',
  'NZ-STL': 'Southland',
  'NZ-TKI': 'Taranaki',
  'NZ-TAS': 'Tasman',
  'NZ-WKO': 'Waikato',
  'NZ-WGN': 'Wellington',
  'NZ-WTC': 'West Coast',

  // ── South Africa ──────────────────────────────────────────────────────────
  'ZA-EC': 'Eastern Cape',
  'ZA-FS': 'Free State',
  'ZA-GP': 'Gauteng',
  'ZA-KZN': 'KwaZulu-Natal',
  'ZA-LP': 'Limpopo',
  'ZA-MP': 'Mpumalanga',
  'ZA-NW': 'North West',
  'ZA-NC': 'Northern Cape',
  'ZA-WC': 'Western Cape',

  // ── Argentina ─────────────────────────────────────────────────────────────
  'AR-B': 'Buenos Aires Province',
  'AR-C': 'Buenos Aires City',
  'AR-K': 'Catamarca',
  'AR-H': 'Chaco',
  'AR-U': 'Chubut',
  'AR-X': 'Córdoba',
  'AR-W': 'Corrientes',
  'AR-E': 'Entre Ríos',
  'AR-P': 'Formosa',
  'AR-Y': 'Jujuy',
  'AR-L': 'La Pampa',
  'AR-F': 'La Rioja',
  'AR-M': 'Mendoza',
  'AR-N': 'Misiones',
  'AR-Q': 'Neuquén',
  'AR-R': 'Río Negro',
  'AR-A': 'Salta',
  'AR-J': 'San Juan',
  'AR-D': 'San Luis',
  'AR-Z': 'Santa Cruz',
  'AR-S': 'Santa Fe',
  'AR-G': 'Santiago del Estero',
  'AR-V': 'Tierra del Fuego',
  'AR-T': 'Tucumán',

  // ── Norway ────────────────────────────────────────────────────────────────
  'NO-03': 'Oslo',
  'NO-11': 'Rogaland',
  'NO-15': 'Møre og Romsdal',
  'NO-18': 'Nordland',
  'NO-31': 'Østfold',
  'NO-32': 'Akershus',
  'NO-33': 'Buskerud',
  'NO-34': 'Innlandet',
  'NO-38': 'Vestfold',
  'NO-39': 'Telemark',
  'NO-42': 'Agder',
  'NO-46': 'Vestland',
  'NO-50': 'Trøndelag',
  'NO-55': 'Troms',
  'NO-56': 'Finnmark',

  // ── Sweden ────────────────────────────────────────────────────────────────
  'SE-AB': 'Stockholm County',
  'SE-AC': 'Västernorrland',
  'SE-BD': 'Norrbotten',
  'SE-C': 'Uppsala',
  'SE-D': 'Södermanland',
  'SE-E': 'Östergötland',
  'SE-F': 'Jönköping',
  'SE-G': 'Kronoberg',
  'SE-H': 'Kalmar',
  'SE-I': 'Gotland',
  'SE-K': 'Blekinge',
  'SE-M': 'Skåne',
  'SE-N': 'Halland',
  'SE-O': 'Västra Götaland',
  'SE-S': 'Värmland',
  'SE-T': 'Örebro',
  'SE-U': 'Västmanland',
  'SE-W': 'Dalarna',
  'SE-X': 'Gävleborg',
  'SE-Y': 'Västernorrland',
  'SE-Z': 'Jämtland',

  // ── Denmark ───────────────────────────────────────────────────────────────
  'DK-81': 'North Denmark',
  'DK-82': 'Central Jutland',
  'DK-83': 'Southern Denmark',
  'DK-84': 'Capital Region',
  'DK-85': 'Zealand',

  // ── Finland ───────────────────────────────────────────────────────────────
  'FI-01': 'Uusimaa',
  'FI-02': 'South Karelia',
  'FI-03': 'Southwest Finland',
  'FI-04': 'Satakunta',
  'FI-05': 'Kanta-Häme',
  'FI-06': 'Pirkanmaa',
  'FI-07': 'Päijänne Tavastia',
  'FI-08': 'Kymenlaakso',
  'FI-09': 'South Savo',
  'FI-10': 'North Savo',
  'FI-11': 'North Karelia',
  'FI-12': 'Central Finland',
  'FI-13': 'South Ostrobothnia',
  'FI-14': 'Ostrobothnia',
  'FI-15': 'Central Ostrobothnia',
  'FI-16': 'North Ostrobothnia',
  'FI-17': 'Kainuu',
  'FI-18': 'Lapland',
  'FI-19': 'Åland',

  // ── Poland ────────────────────────────────────────────────────────────────
  'PL-DS': 'Lower Silesia',
  'PL-KP': 'Kuyavian-Pomeranian',
  'PL-LB': 'Lubusz',
  'PL-LD': 'Łódź',
  'PL-LU': 'Lublin',
  'PL-MA': 'Lesser Poland',
  'PL-MZ': 'Masovian',
  'PL-OP': 'Opole',
  'PL-PD': 'Podlaskie',
  'PL-PK': 'Subcarpathian',
  'PL-PM': 'Pomeranian',
  'PL-SK': 'Świętokrzyskie',
  'PL-SL': 'Silesian',
  'PL-WN': 'Warmian-Masurian',
  'PL-WP': 'Greater Poland',
  'PL-ZP': 'West Pomeranian',

  // ── Czech Republic ────────────────────────────────────────────────────────
  'CZ-JC': 'South Bohemia',
  'CZ-JM': 'South Moravia',
  'CZ-KA': 'Karlovy Vary',
  'CZ-KR': 'Hradec Králové',
  'CZ-LI': 'Liberec',
  'CZ-MO': 'Moravia-Silesia',
  'CZ-OL': 'Olomouc',
  'CZ-PA': 'Pardubice',
  'CZ-PL': 'Plzeň',
  'CZ-PR': 'Prague',
  'CZ-ST': 'Central Bohemia',
  'CZ-US': 'Ústí nad Labem',
  'CZ-VY': 'Vysočina',
  'CZ-ZL': 'Zlín',

  // ── Ireland ───────────────────────────────────────────────────────────────
  'IE-C': 'Cork',
  'IE-CE': 'Clare',
  'IE-CN': 'Cavan',
  'IE-CO': 'Cork',
  'IE-CW': 'Carlow',
  'IE-D': 'Dublin',
  'IE-DL': 'Donegal',
  'IE-G': 'Galway',
  'IE-KE': 'Kildare',
  'IE-KK': 'Kilkenny',
  'IE-KY': 'Kerry',
  'IE-LD': 'Longford',
  'IE-LH': 'Louth',
  'IE-LK': 'Limerick',
  'IE-LM': 'Leitrim',
  'IE-LS': 'Laois',
  'IE-MH': 'Meath',
  'IE-MN': 'Monaghan',
  'IE-MO': 'Mayo',
  'IE-OY': 'Offaly',
  'IE-RN': 'Roscommon',
  'IE-SO': 'Sligo',
  'IE-TA': 'Tipperary',
  'IE-WD': 'Waterford',
  'IE-WH': 'Westmeath',
  'IE-WW': 'Wicklow',
  'IE-WX': 'Wexford',

  // ── Turkey ────────────────────────────────────────────────────────────────
  'TR-01': 'Adana',
  'TR-06': 'Ankara',
  'TR-07': 'Antalya',
  'TR-34': 'Istanbul',
  'TR-35': 'İzmir',
  'TR-09': 'Aydın',
  'TR-16': 'Bursa',
  'TR-48': 'Muğla',
  'TR-55': 'Samsun',
  'TR-61': 'Trabzon',
};
