import 'package:shared_models/shared_models.dart';

import '../../core/country_names.dart';
import 'merch_template_ranker.dart';
import 'merch_title_wordbank.dart';
import 'travel_identity.dart';

/// A contextual title and subtitle for a single merch option.
///
/// Generated by [MerchStory.forOption] based on template type, achievement
/// context, country scope, and density class (ADR-154).
class MerchStory {
  const MerchStory({required this.title, required this.subtitle});

  final String title;
  final String subtitle;

  // ── Factory ────────────────────────────────────────────────────────────────

  /// Generates an emotionally engaging story for a merch option.
  ///
  /// [seed] is incremented each time the user presses Regenerate so titles
  /// cycle through the wordbank without consecutive repeats (ADR-157).
  ///
  /// Rules (ADR-157):
  /// - [title] MUST NOT include a country count.
  /// - [subtitle] always starts with "Roavvy:" and always includes country count.
  static MerchStory forOption({
    required CardTemplateType template,
    Achievement? achievement,
    required List<String> codes,
    required MerchDensityClass density,
    required int year,
    TravelIdentityInfo? identity,
    int seed = 0,
  }) {
    if (achievement != null) {
      if (achievement.continentScope != null) {
        return _continentExplorer(template, achievement, codes, identity, seed);
      }
      if (achievement.regionScope != null) {
        return _region(template, achievement, codes, identity, seed);
      }
      if (achievement.category == AchievementCategory.trips &&
          achievement.merch == MerchTriggerType.passportStamp) {
        return _passportMilestone(template, achievement, codes, seed);
      }
      if (achievement.category == AchievementCategory.thisYear) {
        return _year(template, codes, year, seed);
      }
      if (achievement.category == AchievementCategory.countries) {
        return _countries(template, achievement, codes, density, seed);
      }
      if (achievement.category == AchievementCategory.continents) {
        return _continents(template, achievement, codes, seed);
      }
      if (achievement.category == AchievementCategory.trips) {
        return _trips(template, achievement, codes, seed);
      }
    }
    return _generic(template, codes, year, seed);
  }

  // ── Country achievements ───────────────────────────────────────────────────

  static MerchStory _countries(
    CardTemplateType template,
    Achievement achievement,
    List<String> codes,
    MerchDensityClass density,
    int seed,
  ) {
    final n = achievement.progressTarget;
    final countryName = _countryName(codes.firstOrNull);
    final subtitle = MerchTitleWordbank.buildSubtitleLine(codes.length);

    if (n == 1) {
      return switch (template) {
        CardTemplateType.passport => MerchStory(
          title: '$countryName Calling',
          subtitle: subtitle,
        ),
        CardTemplateType.badge => MerchStory(
          title: '$countryName Dreams',
          subtitle: subtitle,
        ),
        CardTemplateType.typography => MerchStory(
          title: countryName,
          subtitle: subtitle,
        ),
        CardTemplateType.heart => MerchStory(
          title: '$countryName \u2014 Heart',
          subtitle: subtitle,
        ),
        CardTemplateType.timeline => MerchStory(
          title: 'Where It Began',
          subtitle: subtitle,
        ),
        _ => MerchStory(title: countryName, subtitle: subtitle),
      };
    }

    // Multi-country milestones — pick from wordbank, no count in title.
    final wordTitle = MerchTitleWordbank.pickGeneric(codes.length, seed);

    return switch (template) {
      CardTemplateType.grid => MerchStory(title: wordTitle, subtitle: subtitle),
      CardTemplateType.passport => MerchStory(
        title: n == 50 ? 'Half the World' : wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.typography => MerchStory(
        title: n == 50 ? 'Half the World' : wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.timeline => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.badge => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.heart => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      _ => MerchStory(title: wordTitle, subtitle: subtitle),
    };
  }

  // ── Continent achievements (breadth) ───────────────────────────────────────

  static MerchStory _continents(
    CardTemplateType template,
    Achievement achievement,
    List<String> codes,
    int seed,
  ) {
    final n = achievement.progressTarget;
    final subtitle = MerchTitleWordbank.buildSubtitleLine(
      codes.length,
      continent: n >= 6 ? null : '$n Continents',
    );
    final wordTitle =
        n >= 6
            ? 'Global Citizen'
            : MerchTitleWordbank.pickGeneric(codes.length, seed);

    return switch (template) {
      CardTemplateType.grid => MerchStory(title: wordTitle, subtitle: subtitle),
      CardTemplateType.typography => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.heart => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.passport => MerchStory(
        title: 'The Grand Tour',
        subtitle: subtitle,
      ),
      CardTemplateType.timeline => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      _ => MerchStory(title: wordTitle, subtitle: subtitle),
    };
  }

  // ── Trip achievements ──────────────────────────────────────────────────────

  static MerchStory _trips(
    CardTemplateType template,
    Achievement achievement,
    List<String> codes,
    int seed,
  ) {
    final n = achievement.progressTarget;
    final tripCtx = n == 1 ? 'First Trip' : '$n Trips';
    final subtitle = MerchTitleWordbank.buildSubtitleLine(
      codes.length,
      tripLabel: tripCtx,
    );
    final wordTitle =
        n == 1 ? 'Where It Began' : MerchTitleWordbank.pickForTrips(seed);

    return switch (template) {
      CardTemplateType.timeline => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.passport => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.grid => MerchStory(title: wordTitle, subtitle: subtitle),
      CardTemplateType.heart => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      _ => MerchStory(title: wordTitle, subtitle: subtitle),
    };
  }

  // ── Year achievements ──────────────────────────────────────────────────────

  static MerchStory _year(
    CardTemplateType template,
    List<String> codes,
    int year,
    int seed,
  ) {
    final subtitle = MerchTitleWordbank.buildSubtitleLine(
      codes.length,
      year: year,
    );
    final wordTitle = MerchTitleWordbank.pickForYear(year, seed);

    return switch (template) {
      CardTemplateType.timeline => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.typography => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.grid => MerchStory(title: wordTitle, subtitle: subtitle),
      CardTemplateType.heart => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.passport => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      _ => MerchStory(title: wordTitle, subtitle: subtitle),
    };
  }

  // ── Continent-explorer achievements ───────────────────────────────────────

  static MerchStory _continentExplorer(
    CardTemplateType template,
    Achievement achievement,
    List<String> codes,
    TravelIdentityInfo? identity,
    int seed,
  ) {
    final continent = achievement.continentScope!;
    final subtitle = MerchTitleWordbank.buildSubtitleLine(
      codes.length,
      continent: continent,
    );
    final wordTitle = MerchTitleWordbank.pickForContinent(continent, seed);

    return switch (template) {
      CardTemplateType.badge => MerchStory(
        title: '$continent Explorer',
        subtitle:
            identity != null
                ? MerchTitleWordbank.buildSubtitleLine(
                  codes.length,
                  continent: continent,
                )
                : subtitle,
      ),
      CardTemplateType.grid => MerchStory(title: wordTitle, subtitle: subtitle),
      CardTemplateType.typography => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.heart => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.passport => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.timeline => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      _ => MerchStory(title: wordTitle, subtitle: subtitle),
    };
  }

  // ── Region achievements ────────────────────────────────────────────────────

  static MerchStory _region(
    CardTemplateType template,
    Achievement achievement,
    List<String> codes,
    TravelIdentityInfo? identity,
    int seed,
  ) {
    final regionKey = achievement.regionScope!;
    final regionName = subRegionDisplayName(regionKey);
    final subtitle = MerchTitleWordbank.buildSubtitleLine(
      codes.length,
      region: regionKey,
    );
    final wordTitle = MerchTitleWordbank.pickForRegion(regionKey, seed);

    return switch (template) {
      CardTemplateType.passport => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.badge => MerchStory(
        title: '$regionName Explorer',
        subtitle: subtitle,
      ),
      CardTemplateType.typography => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.grid => MerchStory(title: wordTitle, subtitle: subtitle),
      CardTemplateType.heart => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.timeline => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      _ => MerchStory(title: wordTitle, subtitle: subtitle),
    };
  }

  // ── Passport milestone achievements ───────────────────────────────────────

  static MerchStory _passportMilestone(
    CardTemplateType template,
    Achievement achievement,
    List<String> codes,
    int seed,
  ) {
    final subtitle = MerchTitleWordbank.buildSubtitleLine(codes.length);
    final wordTitle = MerchTitleWordbank.pickGeneric(codes.length, seed);

    return switch (template) {
      CardTemplateType.passport => MerchStory(
        title: 'Every Entry, Every Exit',
        subtitle: subtitle,
      ),
      CardTemplateType.timeline => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.grid => MerchStory(title: wordTitle, subtitle: subtitle),
      CardTemplateType.heart => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      _ => MerchStory(title: wordTitle, subtitle: subtitle),
    };
  }

  // ── Generic fallback ───────────────────────────────────────────────────────

  static MerchStory _generic(
    CardTemplateType template,
    List<String> codes,
    int year,
    int seed,
  ) {
    final n = codes.length;
    final subtitle = MerchTitleWordbank.buildSubtitleLine(n);
    final wordTitle =
        n == 1
            ? _countryName(codes.firstOrNull)
            : MerchTitleWordbank.pickGeneric(n, seed);

    return switch (template) {
      CardTemplateType.passport => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.grid => MerchStory(title: wordTitle, subtitle: subtitle),
      CardTemplateType.heart => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.timeline => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.typography => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      CardTemplateType.badge => MerchStory(
        title: wordTitle,
        subtitle: subtitle,
      ),
      _ => MerchStory(title: wordTitle, subtitle: subtitle),
    };
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  static String _countryName(String? code) =>
      kCountryNames[code ?? ''] ?? code ?? '';
}
